name: Deploy to the Abyss

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update repo
        uses: actions/checkout@v3
      - name: Stop the bot
        run: docker stop the-r34er
      - name: Build docker container
        run: docker build -t the-res3ar4er .
      - name: Start the bot
        run: docker run --name the-r34er --restart always -d -e THE_R34ER_TOKEN=${{ vars.THE_R34ER_TOKEN }} the-res3ar4er